name: Run

on:
  schedule:
    - cron: "0 15 * * 2"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - name: Run
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: npx ts-node ./src/index.ts

